/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as IndexImport } from './routes/index'
import { Route as EntitiesIndexRouteImport } from './routes/entities/index.route'
import { Route as EntitiesNewRouteImport } from './routes/entities/new.route'
import { Route as EntitiesIdRouteImport } from './routes/entities/$id.route'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const EntitiesIndexRouteRoute = EntitiesIndexRouteImport.update({
  path: '/entities/',
  getParentRoute: () => rootRoute,
} as any)

const EntitiesNewRouteRoute = EntitiesNewRouteImport.update({
  path: '/entities/new',
  getParentRoute: () => rootRoute,
} as any)

const EntitiesIdRouteRoute = EntitiesIdRouteImport.update({
  path: '/entities/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/entities/$id': {
      id: '/entities/$id'
      path: '/entities/$id'
      fullPath: '/entities/$id'
      preLoaderRoute: typeof EntitiesIdRouteImport
      parentRoute: typeof rootRoute
    }
    '/entities/new': {
      id: '/entities/new'
      path: '/entities/new'
      fullPath: '/entities/new'
      preLoaderRoute: typeof EntitiesNewRouteImport
      parentRoute: typeof rootRoute
    }
    '/entities/': {
      id: '/entities/'
      path: '/entities'
      fullPath: '/entities'
      preLoaderRoute: typeof EntitiesIndexRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  LoginRoute,
  EntitiesIdRouteRoute,
  EntitiesNewRouteRoute,
  EntitiesIndexRouteRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.ts",
      "children": [
        "/",
        "/login",
        "/entities/$id",
        "/entities/new",
        "/entities/"
      ]
    },
    "/": {
      "filePath": "index.ts"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/entities/$id": {
      "filePath": "entities/$id.route.tsx"
    },
    "/entities/new": {
      "filePath": "entities/new.route.tsx"
    },
    "/entities/": {
      "filePath": "entities/index.route.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
